### ISSUE TITLE
FR: Browse presets & shift playhead

### ISSUE THREAD

**Issue by tommyw1979** [dozius/TwisterSister#13]
**Describe the solution you'd like**
From the twister4bitwig script there are two things i feel this script really misses, instead of the device specific knobs 7 and 8 which i never use change to "Press to browse presets for selected device Hold to choose category, tag, creator, or results column Press again to commit chosen preset" and also "Shift playhead in 1 bar increments Hold for 1 beat increments | Tap to play/stop"

**Additional context**
thanks

**Comment by dozius** [comment]
Sorry, even if there was room to add these I would never use either of them. I won't be adding these.
