### ISSUE TITLE
SpecificDeviceSettings.toml crash - NoSuchFileException

### ISSUE THREAD

**Issue by thresholdpeople** [dozius/TwisterSister#14]
Before filing a bug report make sure you have followed the [installation instructions](https://github.com/dozius/TwisterSister/blob/main/docs/README.md#installation).

**Describe the bug**
Hello,

I downloaded version 2.0.1, unzipped. I placed in the `~/Documents/Bitwig Studio/Extensions/` folder.  I imported the .mfs profile and uploaded it to the Twister.  

When I launch Bitwig, I immediately get a pop up that says:

```
Twister Sister crashed

java.nio.file.NoSuchFileException: ~/Documents/Bitwig Studio/Extensions/SpecificDeviceSettings.toml
```
And there are buttons to either Disable or Restart.

Pressing restart just generates the same error.

Any ideas?

Thank you!

**Screenshots**
<img width="747" alt="Xnip2023-06-28_20-58-02" src="https://github.com/dozius/TwisterSister/assets/8041470/457714af-b9f1-499c-8682-6c1c3ff9c50e">

**Please complete the following information:**
 - OS: MacOS 11.7.8 Big Sur
 - Bitwig Version: 5.0 beta 13
 - Extension Version: 2.0.1
 - Device Firmware: 08 Jun 2023
 - MIDI Fighter Utility Version: 2.85

**Comment by dozius** [comment]
Did you copy SpecificDeviceSettings.toml to `~/Documents/Bitwig Studio/Extensions/` as per the [installation instructions](https://github.com/dozius/TwisterSister/blob/main/docs/README.md#installation)?

**Comment by thresholdpeople** [comment]
Yep.  I just placed the whole TwisterSister-2.0.1 folder into that directory.
<img width="299" alt="Xnip2023-06-28_22-15-50" src="https://github.com/dozius/TwisterSister/assets/8041470/7ca74eb9-f2a3-4206-9383-cd5b6a282b63">

**Comment by thresholdpeople** [comment]
Ohhhh. I see. I just tried them outside of TwisterSister-2.0.1 and it works now. Sorry about that, I didn't think it'd be an issue.

**Comment by dozius** [comment]
This is not what it says to do in the instructions. Putting them in a
sub-directory is the source of the issue. It's expecting the file in one
location and you have it in another.

**Comment by dozius** [comment]
Oops, I see you already figured it out. :)

**Comment by thresholdpeople** [comment]
Yep, I initially didn't think it would matter if both of those files were in the same folder, even if in a subdirectory.

Thanks for your help!
