### ISSUE TITLE
User Color settings do not show up on bank selection

### ISSUE THREAD

**Issue by Jengamon** [dozius/TwisterSister#16]
**Describe the bug**
User Color settings do not show up on bank selection. When you click to select a bank, where in 4.4.10 it would show the user color numbers, 5.0 does not do this. Would there be an alternative to specifying these colors, while BW figures out what to do with project settings?

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the controller settings icon.
2. Select a bank in the Bank options
3. Observe absence of user color settings

**Expected behaviour**
I expected the color settings to show up.

**Screenshots**
![Screenshot 2023-07-07 at 7 57 42 AM](https://github.com/dozius/TwisterSister/assets/1479994/00bf9077-005c-476c-8b2d-ba7e3f879cae)

**Please complete the following information:**
 - OS: MacOS 13
 - Bitwig Version: 5.0
 - Extension Version: 2.0.1
 - Device Firmware: 08 Jun 2023
 - MIDI Fighter Utility Version: 2.85

**Comment by dozius** [comment]
I was digging into this last week when I upgraded to v5. Seems that document state number settings are completely broken in v5. I haven't had time to put together a bug report and send it to the Bitwig team, but I'll get around to it eventually.

You can still send MIDI directly to the Twister to set the colours if needed. They won't be saved and recalled with the project though.

**Comment by kurasu** [comment]
Yes this was a regression on our end, should be fixed for next bugfix update.

**Comment by dozius** [comment]
Good to know. Thanks for looking into it!

**Comment by Jengamon** [comment]
Fixed in 5.0.1
