### ISSUE TITLE
Fail on Start

### ISSUE THREAD

**Issue by ClaudeEdd** [dozius/TwisterSister#17]
![Capture d'écran 2023-09-27 213234](https://github.com/dozius/TwisterSister/assets/33385441/7cf593e2-24d0-4a0b-a125-e93066ebdc85)

**Describe the bug**
 Since the Bitwig version 5.0 don't load , error msg

**Expected behaviour**
had perfectly doing his job on version 4.x.x

**Screenshots**.

**Please complete the following information:**
 - OS: Windows 11
 - Bitwig Version: 5.0.9
 - Extension Version:2.0.1
 - Device Firmware: 2.Oct. 2019
 - MIDI Fighter Utility Version: : 2.85

**Comment by ClaudeEdd** [comment]
it's Ok, i had two locations of extension directory , one on User\Document and one on User\OneDrive\Document.
Now going perfect ! Thank You

**Comment by JonathanSterne** [comment]
I'm having the same issue.  user/home/documents/bitwig/extensions/ I've reinstalled, I've rebooted.  MacOS 13.4.1, Bitwig 5.0.11
