### ISSUE TITLE
Error when mapping knob 7 & 8 with TOML file

### ISSUE THREAD

**Issue by acousticism** [dozius/TwisterSister#18]
**Describe the bug**
When attempting to map both knob 7 or 8 together or individually, Bitwig produces error at startup:

**Cannot invoke "java.util.List.iterator()" because "settings" is null**

This happens for Bitwig plugins, VST2 and VST3.

**To Reproduce**
1. Edit TOML file to be mapped to any plugin.
2. Open Bitwig

**Expected behaviour**
Tried mapping knobs 7 and 8 to Bitwig, VST2 and VST 3 plugins using Device and Parameter ID's. 

**Screenshots**
![TwisterSisterCrash](https://github.com/dozius/TwisterSister/assets/54112788/763d0013-4aaf-435a-a72b-4ca10b482955)

**Please complete the following information:**
 - OS: Windows 11 Pro 23H2
 - Bitwig Version: 5.1.2
 - Extension Version: 2.0.1
 - Device Firmware: 08 Jun 2023
 - MIDI Fighter Utility Version: 2.85

**Comment by dozius** [comment]
I can't reproduce this. Please attach a `SpecificDeviceSettings.toml` file that causes this issue.

**Comment by acousticism** [comment]
For example, I am trying to map knob 1 to the _Band 1 Frequency_ of the VST 3 version of FabFilter Pro-Q 3.

Device ID = 72C4DB717A4D459AB97E51745D84B39D
Parameter ID = 2

The TOML file has been edited to look like this

```
[controls]
knob1 = ["eq"]

[[vst3]]
id = "72C4DB717A4D459AB97E51745D84B39D"
params.eq = 2
```

Please let me know if there is something I am not doing correctly.

Thanks!

**Comment by dozius** [comment]
Thanks, I am able to reproduce this now. I'll dig into this as soon as I can.

**Comment by acousticism** [comment]
Than you very much!
