### ISSUE TITLE
Add navigation into/out of group tracks

### ISSUE THREAD

**Issue by dozius** [dozius/TwisterSister#5]
Currently there is no way to expand/collapse group tracks, so implementing this feature, while possible, doesn't work well.

The ability to expand/collapse group tracks will be added to the API in Bitwig 4.1. Come back to this feature once it is released.

**Comment by dozius** [comment]
Added in v2.

**Comment by haszari** [comment]
Awesome to have this, I came here looking for a way to deep-dive into nested groups and back out again. I've tested and it's working, but with my multiple nested groups, there might be an issue.

I can navigate down into nested groups, but can't always navigate back out (up). Is this supported? Currently my workaround is to click a top level group to "reset".

@dozius I have some ideas about how it could work. 

- Click to go into group, double-click to go out.
- Click to go into group, shift-click to go out.
- Use left side buttons - button 1 up out, button 3 down into group.

**Comment by dozius** [comment]
Works fine here. Click on a group track to navigate into it, click on any track in the group to navigate out. I can't reproduce any situation where I'm stuck in a group, no matter how many levels deep I make the groups. If you think you've encountered a bug, I'd suggest open a new bug report with steps to reproduce and all the other information the template asks for.

**Comment by haszari** [comment]
Thanks for confirming it's working / supported (and so quick!). I'll do some more thorough testing 🚀
