### ISSUE TITLE
Extension crashes with new version of Bitwig

### ISSUE THREAD

**Issue by marcora** [dozius/TwisterSister#9]
<img width="2032" alt="crash" src="https://user-images.githubusercontent.com/6343/231620147-5819d5eb-9128-49da-a002-c387723d2eef.png">

**Comment by marcora** [comment]
Thanks! I am happy to test once you find the time to update the extension.
Bitwig should give you a free update plan!

**Comment by dozius** [comment]
@marcora I think this should fix the issue. Let me know if it does and I'll release a new version with these changes. Thanks!

[TwisterSister-2.0.1_testbuild.zip](https://github.com/dozius/TwisterSister/files/11236787/TwisterSister-2.0.1_testbuild.zip)

**Comment by sapre2314** [comment]
The specific crash mentioned above has been fixed. I can use it in Bitwig 5 Beta 3. Thanks for the script! It is really helpful and I use it almost every day
